version: "3.9"

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    environment:
      ORACLE_PASSWORD: oracle
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - ./db/init:/container-entrypoint-initdb.d
    ports:
      - "1521:1521"
  airflow:
    build: ./airflow
    env_file: .env
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"