version: "3.9"

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    environment:
      ORACLE_PASSWORD: oracle
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - ./db/init:/container-entrypoint-initdb.d
    ports:
      - "1521:1521"
  airflow:
    image: apache/airflow:2.8.1-python3.10
    container_name: airflow
    restart: unless-stopped
    env_file: .env
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      _PIP_ADDITIONAL_REQUIREMENTS: "cx_Oracle"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/src:/opt/airflow/src
    ports:
      - "8080:8080"
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --firstname Admin --lastname Admin --role Admin --email admin@example.com --password admin || true &&
        airflow scheduler &
        exec airflow webserver
      "
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
  web:
    build: ./web
    container_name: campaign_web
    depends_on:
      - oracle-db
      - redis
      - airflow
    env_file: .env
    ports:
      - "8501:8501"
