services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    env_file: .env
    volumes:
      - ./db/init:/container-entrypoint-initdb.d
    ports:
      - "1521:1521"
  airflow:
    image: apache/airflow:2.8.1-python3.10
    container_name: airflow
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/src:/opt/airflow/src
    ports:
      - "8080:8080"
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --firstname Admin --lastname Admin --role Admin --email admin@example.com --password admin || true &&
        airflow scheduler &
        exec airflow webserver
      "
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
  web1:
    build: ./web
    image: web:latest
    container_name: campaign_web
    depends_on:
      - oracle-db
      - redis
      - airflow
    env_file: .env
    ports:
      - "8501:8501"
  web2:
    image: web:latest
    container_name: campaign_web2
    environment:
      STREAMLIT_SERVER_PORT: 8502
    ports:
      - "8502:8502"
    restart: always
    depends_on:
      - oracle-db
      - redis
    env_file: .env
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - web1
      - redis
      - redis-exporter
      - oracle-db
      - oracle-exporter
  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file: .env
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
  oracle-exporter:
    image: iamseth/oracledb_exporter:latest
    container_name: oracle-exporter
    env_file: .env
    environment:
      DATA_SOURCE_NAME: system/oracle@oracle-db:1521/XE
    ports: [ "9161:9161" ]
    restart: unless-stopped
    depends_on:
      - oracle-db
    volumes:
      - ./monitoring/custom-metrics.toml:/etc/custom-metrics.toml
    command: [ "--custom.metrics=/etc/custom-metrics.toml" ]
  redis-exporter:
    image: oliver006/redis_exporter:v1.54.0
    container_name: redis-exporter
    command: [ "--redis.addr=redis://redis:6379" ]
    ports:
      - "9121:9121"
    restart: unless-stopped
    depends_on:
      - redis