global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'web_app'
    static_configs:
      - targets: ['web1:8001']
      - targets: ['web2:8001']

  - job_name: 'oracle_db'
    static_configs:
      - targets: ['oracle-exporter:9161']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
